### ISSUE TITLE
Invidious Instance not loading

### ISSUE THREAD

**Issue by StarsOnMars** [antonic901/xbox-youtube#4]
I've written about this on YouTube, but I'm hosting an Invidious Instance on DigitalOcean that doesn't have HTTPS enabled, for the plug-in to be standalone, and curbs the need for a PC back-end. However, it can pull everything from the server, but not load it.

Instance: [omitted]

**Comment by antonic901** [comment]
There was a problem in function getVideoLink in invidious.py. It was dependant on Gateway and because of that link couldn't be generated. I fixed that and you can see what I've changed on develop branch in latest commit. What I actually did? Well I didn't change anything special, I've only added option in settings so user can decide if he wants to use direct connection to invidious or gateway between Xbox and invidious.

P.S. If you can edit your message above, please remove link to your instance. The less people knows about this public instance, better for us. It should only be used for you and OG Xbox users.

And one more bug I find out while testing. Images are not loading. For more info see two pictures below. On upper picture is your instance, and on lower is public instance from Invidious table.

![Local](https://i.postimg.cc/GtQntgYG/Screenshot-from-2022-07-24-01-24-57.png)
![Official](https://i.postimg.cc/xjy26878/Screenshot-from-2022-07-24-01-30-30.png)


As you can see, for some reason your instance is not appending "omitted" to image url link. If you can fix it, that would be great :D

You can download new plugin from develop branch, it's located in Xbox>plugins>video
Also be sure  to delete old plugin from your Xbox and also to delete plugin settings (Q:\UserData\profiles\profile_name\plugin_data\video)

**Comment by StarsOnMars** [comment]
Is that in a file for the plugin, or is that inspect element screenshots from both instances?

**Comment by antonic901** [comment]
Images are taken from Postman response. On first image is response from your instance and on second is response from vid.puffyan.us instance.

**Comment by antonic901** [comment]
I've fixed problem when images are not loading. Please test plugin and report if everything is alright so I can merge on master and publish new version.

**Comment by StarsOnMars** [comment]
The plugin is working, thumbnails are popping up perfectly, and I'm able to move to view videos from the instance without any issues. Unless adaptive streaming is somehow figured out for this plugin, I don't know what else would need to be worked on. Everything's working fine, now I'll try to fix/remake a weather plugin for XBMC4XBOX.

**Comment by antonic901** [comment]
Nice, I will release tomorrow new version. I've read through Invidious documentation and I find out that 480p and 1080p are possible but you need to apped &quality=dash to url link, but it's resource heavily so it's disabled by default.

**Comment by StarsOnMars** [comment]
Would they still be functional with the formative streaming?

**Comment by antonic901** [comment]
Now I see, DASH is actually  from "Dynamic Adaptive Streaming over HTTP". Well we will see if I ever implement that, but honestly, it's not worth it. 480p maybe, but 1080p is definitly not beacuse Xbox can't handle that.
